# Generated by Django 5.2.7 on 2025-11-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
